apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
spec:
  rules:
  - host: itkmitl.bookinfo.dev.opsta.net
    http:
      paths:
      - path: /student13/ratings(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8080